name: Admin-GUI
version: 1.4.7
main: com.rabbitcompany.admingui.AdminGUI
api-version: 1.13
authors: [RabbitCompany]
description: Easy manage your Minecraft server with Admin GUI
softdepend: [Vault, SuperVanish, PremiumVanish]
commands:
  admin:
    usage: /<command>
    description: Show Admin GUIs